name: CI/CD Pipeline
run-name: Pipeline executed by ${{ github.actor }}, run-number ${{ github.run_number }}
on:
  workflow_dispatch:
#  push:
#    branches:
#      - main
jobs:
  Build:
    name: Code build job
    runs-on: ubuntu-latest
    steps:
      - name: Code checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
          
      - name: .NET Build project
        working-directory: ./src
        run: dotnet build Review-Filmes.sln

  Tests:
    needs: [Build]
    uses: LucasGLGoncalves/movie-review-app/.github/workflows/tests.yml@main
    secrets: inherit
  
  Release:
    needs: [Tests]
    name: Create code release
    runs-on: ubuntu-latest
    steps:
      - name: Code checkout
        uses: actions/checkout@v4

      - name: Hadolint dockerfile compliance check
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: ./src/Review-Filmes.Web/Dockerfile

      - name: Docker login
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker build and push
        uses: docker/build-push-action@v6
        with:
          context: ./src
          file: ./src/Review-Filmes.Web/Dockerfile
          push: true
          tags: |
            rukasu/movie-review-app:latest
            rukasu/movie-review-app:v${{ github.run_number }}
      
      - name: Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.28.0
        with:
          scan-type: image
          image-ref: 'rukasu/movie-review-app:v${{ github.run_number }}'
          format: sarif
          output: trivy-docker-result.sarif
          severity: 'UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL'
          #exit-code: '1'
          #ignore-unfixed: true
          #vuln-type: 'os,library'

      - name: Upload trivy scan file to Github
        uses: github/codeql-action/upload-sarif@v3
        with:
          category: docker-result
          sarif_file: trivy-docker-result.sarif
