name: CI/CD Pipeline
run-name: Pipeline executed by ${{ github.actor }}, run-number ${{ github.run_number }}
on:
  workflow_dispatch:
#  push:
#    branches:
#      - main
jobs:
  Build:
    name: Code build job
    runs-on: ubuntu-latest
    steps:
      - name: Code checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
          
      - name: .NET Build project
        working-directory: ./src
        run: dotnet build Review-Filmes.sln
  
  Release:
    needs: ['Build']
    name: Create code release
    runs-on: ubuntu-latest
    steps:
      - name: Code checkout
        uses: actions/checkout@v4

      - name: Docker login
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker build and push
        uses: docker/build-push-action@v6
        with:
          context: ./src
          file: ./src/Review-Filmes.Web/Dockerfile
          push: true
          tags: |
            rukasu/movie-review-app:latest
            rukasu/movie-review-app:v${{ github.run_number }}
        
